[2025-10-05T04:29:55.749+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-10-05T04:29:55.760+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T04:20:00+00:00 [queued]>
[2025-10-05T04:29:55.764+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T04:20:00+00:00 [queued]>
[2025-10-05T04:29:55.764+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 3
[2025-10-05T04:29:55.771+0000] {taskinstance.py:2888} INFO - Executing <Task(_PythonDecoratedOperator): train_and_log_models> on 2025-10-05 04:20:00+00:00
[2025-10-05T04:29:55.777+0000] {standard_task_runner.py:72} INFO - Started process 608 to run task
[2025-10-05T04:29:55.779+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'forest_cover_mlops_pipeline', 'train_and_log_models', 'scheduled__2025-10-05T04:20:00+00:00', '--job-id', '6', '--raw', '--subdir', 'DAGS_FOLDER/forest_cover_dag.py', '--cfg-path', '/home/airflow/tmp/tmpxlq_wag5']
[2025-10-05T04:29:55.780+0000] {standard_task_runner.py:105} INFO - Job 6: Subtask train_and_log_models
[2025-10-05T04:29:55.816+0000] {task_command.py:467} INFO - Running <TaskInstance: forest_cover_mlops_pipeline.train_and_log_models scheduled__2025-10-05T04:20:00+00:00 [running]> on host 6099a2463998
[2025-10-05T04:29:55.964+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='mlops-team' AIRFLOW_CTX_DAG_ID='forest_cover_mlops_pipeline' AIRFLOW_CTX_TASK_ID='train_and_log_models' AIRFLOW_CTX_EXECUTION_DATE='2025-10-05T04:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-10-05T04:20:00+00:00'
[2025-10-05T04:29:55.965+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-10-05T04:29:56.328+0000] {logging_mixin.py:190} INFO - Entrenando 3 modelos con GridSearchCV...
[2025-10-05T04:29:56.328+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T04:29:56.329+0000] {logging_mixin.py:190} INFO - Modelo: RandomForest
[2025-10-05T04:29:56.329+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T04:29:56.348+0000] {logging_mixin.py:190} WARNING - 2025/10/05 04:29:56 WARNING mlflow.utils.git_utils: Failed to import Git (the Git executable is probably not on your PATH), so Git SHA is not available. Error: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh(<full-path-to-git-executable>)

All git commands will error until this is rectified.

This initial message can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|silent|none|n|0: for no message or exception
    - warn|w|warning|log|l|1: for a warning message (logging level CRITICAL, displayed by default)
    - error|e|exception|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet
[2025-10-05T04:29:56.470+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T04:29:56.470+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 12 candidates, totalling 36 fits
[2025-10-05T04:30:04.200+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__max_depth': 20, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 50}
[2025-10-05T04:30:04.679+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 0.9996
[2025-10-05T04:30:04.679+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.8941
[2025-10-05T04:30:04.679+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.8923
[2025-10-05T04:30:04.679+0000] {logging_mixin.py:190} INFO -   CV Score: 0.8830 (+/- 0.0056)
[2025-10-05T04:30:06.635+0000] {logging_mixin.py:190} WARNING - 2025/10/05 04:30:06 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T04:30:06.809+0000] {credentials.py:1147} INFO - Found credentials in environment variables.
[2025-10-05T04:30:07.016+0000] {logging_mixin.py:190} WARNING - Successfully registered model 'forest_cover_randomforest'.
[2025-10-05T04:30:07.035+0000] {logging_mixin.py:190} WARNING - 2025/10/05 04:30:07 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_randomforest, version 1
[2025-10-05T04:30:07.035+0000] {logging_mixin.py:190} WARNING - Created version '1' of model 'forest_cover_randomforest'.
[2025-10-05T04:30:07.059+0000] {logging_mixin.py:190} WARNING - 2025/10/05 04:30:07 INFO mlflow.tracking._tracking_service.client: üèÉ View run RandomForest_batch_1 at: http://mlflow:5000/#/experiments/1/runs/4ada8791965243f18db37bbbf4b50da2.
[2025-10-05T04:30:07.060+0000] {logging_mixin.py:190} WARNING - 2025/10/05 04:30:07 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T04:30:07.084+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T04:30:07.085+0000] {logging_mixin.py:190} INFO - Modelo: GradientBoosting
[2025-10-05T04:30:07.085+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T04:30:07.211+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T04:30:07.212+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 8 candidates, totalling 24 fits
[2025-10-05T04:31:17.351+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__learning_rate': 0.1, 'classifier__max_depth': 5, 'classifier__n_estimators': 100}
[2025-10-05T04:31:31.042+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 0.9953
[2025-10-05T04:31:31.043+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.8907
[2025-10-05T04:31:31.043+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.8901
[2025-10-05T04:31:31.043+0000] {logging_mixin.py:190} INFO -   CV Score: 0.8782 (+/- 0.0056)
[2025-10-05T04:31:32.546+0000] {logging_mixin.py:190} WARNING - 2025/10/05 04:31:32 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T04:31:32.643+0000] {logging_mixin.py:190} WARNING - Successfully registered model 'forest_cover_gradientboosting'.
[2025-10-05T04:31:32.713+0000] {logging_mixin.py:190} WARNING - 2025/10/05 04:31:32 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_gradientboosting, version 1
[2025-10-05T04:31:32.714+0000] {logging_mixin.py:190} WARNING - Created version '1' of model 'forest_cover_gradientboosting'.
[2025-10-05T04:31:32.744+0000] {logging_mixin.py:190} WARNING - 2025/10/05 04:31:32 INFO mlflow.tracking._tracking_service.client: üèÉ View run GradientBoosting_batch_1 at: http://mlflow:5000/#/experiments/1/runs/3158ff0d50164f5a9b675d55ab36ce19.
[2025-10-05T04:31:32.744+0000] {logging_mixin.py:190} WARNING - 2025/10/05 04:31:32 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T04:31:32.770+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T04:31:32.771+0000] {logging_mixin.py:190} INFO - Modelo: LogisticRegression
[2025-10-05T04:31:32.771+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T04:31:32.889+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/joblib/parallel.py:1379: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(

[2025-10-05T04:31:32.889+0000] {logging_mixin.py:190} INFO - Fitting 3 folds for each of 6 candidates, totalling 18 fits
[2025-10-05T04:31:35.587+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T04:31:36.216+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T04:31:37.192+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T04:31:37.192+0000] {logging_mixin.py:190} INFO -   Mejores par√°metros: {'classifier__C': 10.0, 'classifier__solver': 'saga'}
[2025-10-05T04:31:38.525+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T04:31:39.193+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.11/site-packages/sklearn/linear_model/_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(

[2025-10-05T04:31:39.194+0000] {logging_mixin.py:190} INFO -   Train Accuracy: 0.7666
[2025-10-05T04:31:39.195+0000] {logging_mixin.py:190} INFO -   Test Accuracy: 0.7625
[2025-10-05T04:31:39.195+0000] {logging_mixin.py:190} INFO -   Test F1 (weighted): 0.7532
[2025-10-05T04:31:39.195+0000] {logging_mixin.py:190} INFO -   CV Score: 0.7595 (+/- 0.0098)
[2025-10-05T04:31:40.608+0000] {logging_mixin.py:190} WARNING - 2025/10/05 04:31:40 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.
[2025-10-05T04:31:40.663+0000] {logging_mixin.py:190} WARNING - Successfully registered model 'forest_cover_logisticregression'.
[2025-10-05T04:31:40.691+0000] {logging_mixin.py:190} WARNING - 2025/10/05 04:31:40 INFO mlflow.store.model_registry.abstract_store: Waiting up to 300 seconds for model version to finish creation. Model name: forest_cover_logisticregression, version 1
[2025-10-05T04:31:40.692+0000] {logging_mixin.py:190} WARNING - Created version '1' of model 'forest_cover_logisticregression'.
[2025-10-05T04:31:40.706+0000] {logging_mixin.py:190} WARNING - 2025/10/05 04:31:40 INFO mlflow.tracking._tracking_service.client: üèÉ View run LogisticRegression_batch_1 at: http://mlflow:5000/#/experiments/1/runs/473fd1e9d8644f08beac4f99880bdbe8.
[2025-10-05T04:31:40.706+0000] {logging_mixin.py:190} WARNING - 2025/10/05 04:31:40 INFO mlflow.tracking._tracking_service.client: üß™ View experiment at: http://mlflow:5000/#/experiments/1.
[2025-10-05T04:31:40.716+0000] {logging_mixin.py:190} INFO - 
==================================================
[2025-10-05T04:31:40.716+0000] {logging_mixin.py:190} INFO - ‚úì Entrenamiento completado
[2025-10-05T04:31:40.717+0000] {logging_mixin.py:190} INFO -   Mejor modelo: RandomForest (Accuracy: 0.8941)
[2025-10-05T04:31:40.717+0000] {logging_mixin.py:190} INFO - ==================================================
[2025-10-05T04:31:40.717+0000] {python.py:240} INFO - Done. Returned value was: {'results': {'RandomForest': {'test_accuracy': 0.8941480206540448, 'test_f1_weighted': 0.8923359429218999, 'cv_mean_score': 0.8829600783023386, 'best_params': {'classifier__max_depth': 20, 'classifier__min_samples_split': 2, 'classifier__n_estimators': 50}}, 'GradientBoosting': {'test_accuracy': 0.8907056798623064, 'test_f1_weighted': 0.8900976944294461, 'cv_mean_score': 0.8782288955066399, 'best_params': {'classifier__learning_rate': 0.1, 'classifier__max_depth': 5, 'classifier__n_estimators': 100}}, 'LogisticRegression': {'test_accuracy': 0.7624784853700516, 'test_f1_weighted': 0.7531729405832533, 'cv_mean_score': 0.7594647951852392, 'best_params': {'classifier__C': 10.0, 'classifier__solver': 'saga'}}}, 'best_model': 'RandomForest', 'best_score': 0.8941480206540448, 'experiment_name': 'forest_cover_classification', 'mlflow_uri': 'http://mlflow:5000'}
[2025-10-05T04:31:40.740+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-10-05T04:31:40.740+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=forest_cover_mlops_pipeline, task_id=train_and_log_models, run_id=scheduled__2025-10-05T04:20:00+00:00, execution_date=20251005T042000, start_date=20251005T042955, end_date=20251005T043140
[2025-10-05T04:31:40.765+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-10-05T04:31:40.785+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-10-05T04:31:40.785+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-10-05T04:31:40.786+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
